name: Build & Deploy to Docker + S3 + CloudFront

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout
            uses: actions/checkout@v3

          - name: Configure AWS credentials
            uses: aws-actions/configure-aws-credentials@v2
            with:
              aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
              aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
              aws-region: ${{ secrets.AWS_REGION }}

          - name: Login to Amazon ECR
            id: login-ecr
            uses: aws-actions/amazon-ecr-login@v2

          - name: Build, tag, and push image to ECR
            env:
              ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORIES }}
            run: |
              docker build -t $ECR_REPOSITORIES:latest .
              docker push $ECR_REPOSITORIES:latest

          - name: Force new ECS deployment
            run: |
              aws ecs update-service \
                --cluster ${{ secrets.CLUSTER_NAME }} \
                --service ${{ secrets.SERVICE_NAME }} \
                --force-new-deployment