name: Build & Deploy to Docker + S3 + CloudFront

on:
    push:
        branches:
            - main

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set up node.js
              uses: actions/setup-node@v3
              with:
                node-version: "18"

            - name: Install Dependencies
              run: npm install

            - name: Build Project
              run: npm run build

            - name: Build Docker Image
              run: docker build -t ${{ secrets.DOCKER_USERNAME }}/my-next-portfolio .

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                username: ${{ secrets.DOCKER_USERNAME }}
                password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Push Docker Image to Docker Hub
              run: docker push ${{ secrets.DOCKER_USERNAME }}/my-next-portfolio

            - name: Upload static files to S3
              uses: jakejarvis/s3-sync-action@master
              with:
                args: --delete
              env:
                AWS_S3_BUCKET: ${{ secrets.S3_BUCKET_NAME }}
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
                AWS_REGION: ${{ secrets.AWS_REGION }}
                SOURCE_DIR: ".next/static"

            - name: Invalidate CloudFront cache
              uses: chetan/invalidate-cloudfront-action@v2
              env:
                DISTRIBUTION: ${{ secrets.DISTRIBUTION_ID }}
                PATHS: "/*"
                AWS_REGION: ${{ secrets.AWS_REGION }}
                AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
                AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
